### ISSUE TITLE
My ID doesnt work

### ISSUE THREAD

**Issue by muzzak123** [yaleman/goodwe2pvoutput#13]
I have entered my SystemID in the config but when I run goodwe2pvoutput I get an error message 
"Need to specify goodwe systemid in config"
I have noticed my System ID format is slightly different to the example  11112222-aaaa-bbbb-cccc-ddddeeeeeffff
Mine exactly matches up to the last part of "ddddeeeeeffff" where mine is only 12 characters. The same id is working fine in my other automations.

**Comment by yaleman** [comment]
Hi, can you please provide a redacted (ie, with your personal details obscured) version of the config file you've created? The check that you're hitting doesn't actually look at the value, it's just checking that the config option is set at all.

It should look similar to this, the key parts are not changing the things before the equals sign.
```
[goodwe]
account = user@example.com
system_id = aaabbbbb-cccc-dddd-eeee-ffffffgggggg
password = darkHorseBatteryStaple123
```

**Comment by muzzak123** [comment]
Sure, my config is in ~/.goodwe2pvoutput.conf
and looks like ...

[default]
...

[goodwe]
account = mmmm@blog.xxx.com
system_id = b12480e9-9474-4cae-8c43-5b0b55c95572
password = secretstuff

[pvoutput]
apikey = xxxxxxxxxxxxxxxxxxxxxxxxxxx
systemid = 1234
donation_made = False
schedule_time = 10

**Comment by yaleman** [comment]
Ah, I found a typo in my example, I'm guessing I changed something and didn't notice - `system_id` needs to be `systemid`.

**Comment by muzzak123** [comment]
That works, Thanks for that and the project. Just a quick question. What data fields from Goodwe does this upload to PVOutput ?
ie does it include Voltage and Temperature ?

**Comment by yaleman** [comment]
Yep, grabs generation, load, inverter temperature and voltage. If you're a subscriber to pvoutput you can store state of charge of your battery too. The data is pulled via my pygoodwe library in this function: https://github.com/yaleman/pygoodwe/blob/master/pygoodwe/__init__.py#L236

**Comment by muzzak123** [comment]
OK - all working good now, however I seem to be getting Power Used and hence Energy Used as well, with the Power Used value exactly equalling the Power Generated ? Since the inverter can't know how much power I'm using shouldn't this be null or zero ?

**Comment by yaleman** [comment]
Why wouldn't the inverter know this? My GoodWe has a full view because there's a sensor on several points of the feed and all power goes through it.

**Comment by muzzak123** [comment]
My inverter is attached between the solar panels and the power to my house. Hence the Power Generated figure is how much the solar panels are generating. The Power Used (in PVOutput) shows how much the House is using. This is different from the generation, since say at night the Power Generated will drop to 0, but the house is still using power so Power Used won't be zero and it will be coming from the grid. Probably because you have a battery you don't see this as you draw power from you battery.

The Power Used figure should come from something that monitors how much power is going into the house. I used to have one of these meters but now I have a 3 phase system it not longer works. This is how my PVOutput used to look like. As you can see the Power Used (Red line) fluctuates as things go on and off. 
![Untitled](https://user-images.githubusercontent.com/51472089/103979269-6a0cfb00-51b8-11eb-8927-f5491173a878.png)

**Comment by yaleman** [comment]
I don't control the data coming from the GoodWe API, that's something you'd need to work out with them...

**Comment by muzzak123** [comment]
Can I disable the Power Used feed in goodwe2pvoutput ?  If so how ?

**Comment by yaleman** [comment]
There's no configurable option currently, but you're welcome to provide a PR that does it, or if you just want do it for yourself, just after the data's queried in the line I referenced earlier, delete the data from API response and it won't be passed to PVOutput.

It should be field v4 (ref: https://pvoutput.org/help.html#api-addstatus)

**Comment by muzzak123** [comment]
Thanks, I deleted line 253 and it's working now. 
Thanks for your help
